/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stampplayer;

import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Asus
 */
public class StampPlayerMain extends javax.swing.JFrame {

  /**
   * Creates new form StampPlayer2
   */
  public StampPlayerMain() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    slideTime = new javax.swing.JSlider();
    jPanel7 = new javax.swing.JPanel();
    slideVolume = new javax.swing.JSlider();
    lblTime = new javax.swing.JLabel();
    jPanel8 = new javax.swing.JPanel();
    btnPrevious = new javax.swing.JButton();
    btnStop = new javax.swing.JButton();
    btnPlay = new javax.swing.JButton();
    btnPause = new javax.swing.JButton();
    btnNext = new javax.swing.JButton();
    tglbtnMute = new javax.swing.JToggleButton();
    jPanel3 = new javax.swing.JPanel();
    txtSearch = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    listPlaylist = new javax.swing.JList();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    btnSelect = new javax.swing.JButton();
    btnUnselect = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    btnRemove = new javax.swing.JButton();
    btnAddFile = new javax.swing.JButton();
    jMenuBar2 = new javax.swing.JMenuBar();
    menuFile = new javax.swing.JMenu();
    menuOpenPlaylist = new javax.swing.JMenuItem();
    menuSavePlaylist = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    menuExit = new javax.swing.JMenuItem();
    menuService = new javax.swing.JMenu();
    menuChangeSkin = new javax.swing.JMenu();
    AluminiumMenuSkin = new javax.swing.JRadioButtonMenuItem();
    FastMenuSkin = new javax.swing.JRadioButtonMenuItem();
    MintMenuSkin = new javax.swing.JRadioButtonMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("StampPlayer");
    setMinimumSize(new java.awt.Dimension(400, 500));

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel2.setMinimumSize(new java.awt.Dimension(380, 120));
    jPanel2.setPreferredSize(new java.awt.Dimension(380, 120));

    slideTime.setValue(0);

    slideVolume.setOrientation(javax.swing.JSlider.VERTICAL);
    slideVolume.setValue(70);

    lblTime.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
    lblTime.setText("12:33");

    btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/previous.png"))); // NOI18N
    btnPrevious.setToolTipText("previous");
    btnPrevious.setMargin(new java.awt.Insets(2, 2, 2, 2));

    btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stop.png"))); // NOI18N
    btnStop.setToolTipText("stop");
    btnStop.setMargin(new java.awt.Insets(2, 2, 2, 2));

    btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/play.png"))); // NOI18N
    btnPlay.setToolTipText("play");
    btnPlay.setMargin(new java.awt.Insets(2, 2, 2, 2));

    btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pause.png"))); // NOI18N
    btnPause.setToolTipText("pause");
    btnPause.setMargin(new java.awt.Insets(2, 2, 2, 2));

    btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
    btnNext.setToolTipText("next");
    btnNext.setMargin(new java.awt.Insets(2, 2, 2, 2));

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnPrevious)
      .addComponent(btnStop)
      .addComponent(btnPlay)
      .addComponent(btnPause)
      .addComponent(btnNext)
    );

    tglbtnMute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/speaker.png"))); // NOI18N
    tglbtnMute.setDisabledIcon(null);
    tglbtnMute.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mute.png"))); // NOI18N
    tglbtnMute.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/speaker.png"))); // NOI18N
    tglbtnMute.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mute.png"))); // NOI18N

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel7Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTime)
        .addGap(18, 18, 18)
        .addComponent(slideVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tglbtnMute, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(slideVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(tglbtnMute, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(slideTime, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(slideTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(23, 23, 23))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    txtSearch.setMaximumSize(new java.awt.Dimension(6, 20));
    txtSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchActionPerformed(evt);
      }
    });

    btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });

    listPlaylist.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    listPlaylist.setFixedCellHeight(22);
    jScrollPane2.setViewportView(listPlaylist);

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

    btnSelect.setText("Sel");
    btnSelect.setToolTipText("Select All");
    btnSelect.setMargin(new java.awt.Insets(2, 4, 2, 4));
    btnSelect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSelectActionPerformed(evt);
      }
    });
    jPanel5.add(btnSelect);

    btnUnselect.setText("Unsel");
    btnUnselect.setToolTipText("Unselect All");
    btnUnselect.setMargin(new java.awt.Insets(2, 4, 2, 4));
    jPanel5.add(btnUnselect);

    jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

    btnRemove.setText("Remove");
    btnRemove.setToolTipText("Remove File");
    btnRemove.setMargin(new java.awt.Insets(2, 4, 2, 4));
    btnRemove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRemoveActionPerformed(evt);
      }
    });
    jPanel6.add(btnRemove);

    btnAddFile.setText("Add...");
    btnAddFile.setToolTipText("Add Files");
    btnAddFile.setMargin(new java.awt.Insets(2, 4, 2, 4));
    jPanel6.add(btnAddFile);
    btnAddFile.getAccessibleContext().setAccessibleDescription("Add new File");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jScrollPane2)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(1, 1, 1))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menuFile.setText("File");

    menuOpenPlaylist.setText("Open playlist");
    menuOpenPlaylist.setToolTipText("");
    menuOpenPlaylist.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuOpenPlaylistActionPerformed(evt);
      }
    });
    menuFile.add(menuOpenPlaylist);

    menuSavePlaylist.setText("Save playlist");
    menuFile.add(menuSavePlaylist);
    menuFile.add(jSeparator1);

    menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
    menuExit.setText("Exit");
    menuFile.add(menuExit);

    jMenuBar2.add(menuFile);

    menuService.setText("Service");

    menuChangeSkin.setText("Change Skin");
    menuChangeSkin.setToolTipText("Change skin");

    buttonGroup1.add(AluminiumMenuSkin);
    AluminiumMenuSkin.setSelected(true);
    AluminiumMenuSkin.setText("Aluminium");
    AluminiumMenuSkin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AluminiumMenuSkinActionPerformed(evt);
      }
    });
    menuChangeSkin.add(AluminiumMenuSkin);

    buttonGroup1.add(FastMenuSkin);
    FastMenuSkin.setText("Fast");
    FastMenuSkin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        FastMenuSkinActionPerformed(evt);
      }
    });
    menuChangeSkin.add(FastMenuSkin);

    buttonGroup1.add(MintMenuSkin);
    MintMenuSkin.setText("Mint");
    MintMenuSkin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MintMenuSkinActionPerformed(evt);
      }
    });
    menuChangeSkin.add(MintMenuSkin);

    menuService.add(menuChangeSkin);

    jMenuBar2.add(menuService);

    setJMenuBar(jMenuBar2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuOpenPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenPlaylistActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_menuOpenPlaylistActionPerformed

  private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSelectActionPerformed

  private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnRemoveActionPerformed

  private void FastMenuSkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FastMenuSkinActionPerformed
    try {
      UIManager.setLookAndFeel( new FastLookAndFeel());
    } catch (UnsupportedLookAndFeelException ex) {
      Logger.getLogger(StampPlayerMain.class.getName()).log(Level.SEVERE, null, ex);
    }
    SwingUtilities.updateComponentTreeUI( this);
  }//GEN-LAST:event_FastMenuSkinActionPerformed

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSearchActionPerformed

  private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchActionPerformed

  private void AluminiumMenuSkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AluminiumMenuSkinActionPerformed
    try {
      UIManager.setLookAndFeel( new AluminiumLookAndFeel());
    } catch (UnsupportedLookAndFeelException ex) {
      Logger.getLogger(StampPlayerMain.class.getName()).log(Level.SEVERE, null, ex);
    }
    SwingUtilities.updateComponentTreeUI( this);
  }//GEN-LAST:event_AluminiumMenuSkinActionPerformed

  private void MintMenuSkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MintMenuSkinActionPerformed
    try {
      UIManager.setLookAndFeel( new MintLookAndFeel());
    } catch (UnsupportedLookAndFeelException ex) {
      Logger.getLogger(StampPlayerMain.class.getName()).log(Level.SEVERE, null, ex);
    }
    SwingUtilities.updateComponentTreeUI( this);  }//GEN-LAST:event_MintMenuSkinActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(StampPlayerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(StampPlayerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(StampPlayerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(StampPlayerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
    
    
    try {
      javax.swing.UIManager.setLookAndFeel(new AluminiumLookAndFeel());
    } catch (UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(StampPlayerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    StampPlayerMain.setDefaultLookAndFeelDecorated(true);
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new StampPlayerMain().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButtonMenuItem AluminiumMenuSkin;
  private javax.swing.JRadioButtonMenuItem FastMenuSkin;
  private javax.swing.JRadioButtonMenuItem MintMenuSkin;
  private javax.swing.JButton btnAddFile;
  private javax.swing.JButton btnNext;
  private javax.swing.JButton btnPause;
  private javax.swing.JButton btnPlay;
  private javax.swing.JButton btnPrevious;
  private javax.swing.JButton btnRemove;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton btnSelect;
  private javax.swing.JButton btnStop;
  private javax.swing.JButton btnUnselect;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JMenuBar jMenuBar2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JLabel lblTime;
  private javax.swing.JList listPlaylist;
  private javax.swing.JMenu menuChangeSkin;
  private javax.swing.JMenuItem menuExit;
  private javax.swing.JMenu menuFile;
  private javax.swing.JMenuItem menuOpenPlaylist;
  private javax.swing.JMenuItem menuSavePlaylist;
  private javax.swing.JMenu menuService;
  private javax.swing.JSlider slideTime;
  private javax.swing.JSlider slideVolume;
  private javax.swing.JToggleButton tglbtnMute;
  private javax.swing.JTextField txtSearch;
  // End of variables declaration//GEN-END:variables
}
